# 服务器端口配置
server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/online_office?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai"
    username: root
    password: 1110

# mybatis-plus 配置
mybatis-plus:
  # 配置Mapper 映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型的别名
  type-aliases-package: com.online.server.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false

# Mybatis SQL 打印
logging:
  level:
    com.online.server.mapper: debug

jwt:
  # Jwt存储的请求头
  tokenHeader: Authorization
  # Jwt加密秘钥
  secret: feather-ink
  # Jwt 的超期限时间（60*60）*24
  expiration: 86400
  # Jwt负载中拿到开头
  tokenHead: Bearer